language: bash 
services: docker
before_instal:
 - cd 02
 - echo "Welcome docker folder"
script:
 - docker-compose build
before_deploy:
 - echo "${DOCKER_PASSWORD}" | docker login --username "${DOCKER_USERNAME}" --pasword-stdin
deploy:
  provider:script
  script:
    docker push iranfeliciano/rest-with-spring-boot-udemy;
    docker push iranfeliciano/mysql-rest-with-spring-boot-udemy;
  on:
    branch:master
notifications:
 email:false